package controller.fileio.fileoutputcommands;

import model.images.ImageModel;

/**
 * Represents a command for saving an image to an arbitrary file format. Classes which implement
 * this interface will be responsible for specific file formats.
 * @param <T> the image's representation of a pixel.
 */
public interface FileOutputCommand<T> {
  /**
   * Given an image generated by the collage, saves the image to an arbitrary file format.
   * @param image the image to save.
   * @param filePath the path to save the image to.
   * @throws IllegalArgumentException if the image is null or the filePath is not a .ppm file.
   * @throws IllegalStateException if the file is unable to be saved.
   */
  void saveCollageImage(ImageModel<T> image, String filePath);
}
